name: System Monitor CI

on:
  push:
    branches: [ main ]

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run system monitor script
        run: |
          chmod +x linux/system_monitor.sh
          bash linux/system_monitor.sh